### ISSUE TITLE
fix links in README

### ISSUE THREAD

**Issue by jennan** [nesi/snakemake_workshop#26]
Hi, the links to workshop sections in the README are not redirecting anymore to the markdown files. If I remember well, the doc was meant to be browsable either via the rendered website or the github markdown rendered pages.

Maybe we can drop the latter (= remove the direct links to sections from the readme) or make these links pointing to the static website instead of the markdown files?

@DininduSenanayake

**Comment by DininduSenanayake** [comment]
GH markdown pages are more or less obsolete now. Given `MkDocs-material` relies on a number of Python markdown extensions, bare-metal GH .md pages don't look too appetising as some of the syntax will not get rendered to a "sensible" format in gh. 

Therefore, I propose we remove the main README.md page

**Comment by jennan** [comment]
Well README is the entry page for anyone discovering the repository via github... so I would prefer to make it possibly smaller but not to remove it. And putting the link to the rendered material in the README ;-).
